<a href="https://colab.research.google.com/github/sergioelias84/aulas_datascience/blob/desenvolvimento/Aula_Python03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Decisões com Python
# Logica booleana, operadores e condicionais
 Quando o programa começa a tomar caminhos diferentes de acordo com codições.

1. Booleanos

Representa apenas dois estados: True ou False

In [ ]:
maior_de_idade = True
possui_cupom = False

In [2]:
nota = 7.5
frenquencia = 88

print (nota >= 7.0)
print (frenquencia >= 75)

True
True

# Operadores Lógicos

AND = quando todos condições for verdadeiras.

OR = quando uma condição for verdadeira.

NOT = Inverte o resultado.

# Operadores Relacionais

== é igual a?

!= é diferente.

>  É maior.

>= É Maior ou igual.

<  É menor.

<= É Menor ou igual.

In [3]:
nota - 7.0
frequencia = 85
aprovado = nota >= 7.0 and frequencia >= 75
print(aprovado)

True

# if / else

if: Testa a condição e apresenta a condição.

else: Representa o caminho alternativo; O else, atende caso nenhuma condição anterior esteja verdadeira.

In [4]:
nota = 6.5
if nota >= 7:
  print('Aprovado')
else:
  print('Reprovado')

Reprovado

# elif (senão)

Usa quando existem mais de duas possibilidades; O elif significa "senão, se", ou seja;

Ele oferece outra condição quando as anteriores não foram atendidas.

In [9]:
nota = 7
if nota >= 7:
  print('Aprovado')
elif nota >= 5:
  print('Recuperação')
else:
  print('Reprovado')

Aprovado

# Base de alunos
Vamos classificar os alunos por meio da nossa base de dados aluno_desempenho.csv

In [11]:
import pandas as pd
arquivo = '/content/alunos_desempenho.csv'
df = pd.read_csv(arquivo)
df.head()

      aluno  nota_1  nota_2  frequencia
0  Aluno 01    10.0     6.3          51
1  Aluno 02     9.5     9.1          92
2  Aluno 03     8.7     7.3          64
3  Aluno 04     8.4     6.3          81
4  Aluno 05     7.2     4.5          78

# Criando uma função para classificar cada aluno em media e frenquncia

In [15]:
def classificar_aluno(media, frequencia):
    if media >= 7 and frequencia >= 75:
        return 'Aprovado'
    elif media < 7 and frequencia >= 75:
        return 'Reprovado por média'
    elif media >= 7 and frequencia < 75:
        return 'Reprovado por frequência'
    else:
        return 'Reprovado por média e frequência'

df['media'] = (df['nota_1'] + df['nota_2']) / 2

df['situacao'] = df.apply(
    lambda row: classificar_aluno(row['media'], row['frequencia']),
    axis=1
)

df.head()

      aluno  nota_1  nota_2  frequencia  media                  situacao
0  Aluno 01    10.0     6.3          51   8.15  Reprovado por frequência
1  Aluno 02     9.5     9.1          92   9.30                  Aprovado
2  Aluno 03     8.7     7.3          64   8.00  Reprovado por frequência
3  Aluno 04     8.4     6.3          81   7.35                  Aprovado
4  Aluno 05     7.2     4.5          78   5.85       Reprovado por média


Desafio loja
1. Fazer o upload de pedidos_loja.csv e criar uma regra de desconto:
• Cliente VIP recebe 15%
⚫ compra acima de R$ 150 recebe 10%
• quem usou cupom recebe 5%
demais casos não recebem desconto.

In [17]:
import pandas as pd

df = pd.read_csv("pedidos_loja.csv")

df.head()

   pedido_id  valor_compra tipo_cliente  usou_cupom
0          1        253.71         novo       False
1          2        172.95   recorrente       False
2          3        207.40         novo       False
3          4        121.31          vip        True
4          5        113.62   recorrente       False

Criando Função com def;

In [18]:
def calcular_desconto(valor, tipo_cliente, usou_cupom):
    if tipo_cliente == "vip":
        return 0.15
    elif valor > 150:
        return 0.10
    elif usou_cupom:
        return 0.05
    else:
        return 0

Codigo completo

In [20]:
import pandas as pd

df = pd.read_csv("pedidos_loja.csv")

def calcular_desconto(valor, tipo_cliente, usou_cupom):
    if tipo_cliente == "vip":
        return 0.15
    elif valor > 150:
        return 0.10
    elif usou_cupom:
        return 0.05
    else:
        return 0

df["desconto"] = df.apply(
    lambda linha: calcular_desconto(
        linha["valor_compra"],
        linha["tipo_cliente"],
        linha["usou_cupom"]
    ),
    axis=1
)

df["valor_desconto"] = (df["valor_compra"] * df["desconto"]).round(2)

df["valor_final"] = (df["valor_compra"] - df["valor_desconto"]).round(2)

print(df)

    pedido_id  valor_compra tipo_cliente  usou_cupom  desconto  \
0           1        253.71         novo       False      0.10
1           2        172.95   recorrente       False      0.10
2           3        207.40         novo       False      0.10
3           4        121.31          vip        True      0.15
4           5        113.62   recorrente       False      0.00
5           6        198.95         novo        True      0.10
6           7        156.19          vip        True      0.15
7           8         94.26         novo       False      0.00
8           9        245.99   recorrente       False      0.10
9          10        282.44          vip       False      0.15
10         11        132.00          vip       False      0.15
11         12         65.75   recorrente        True      0.05
12         13        256.74          vip       False      0.15
13         14        138.42          vip       False      0.15
14         15        118.46   recorrente       False      0.00
15         16        130.78   recorrente        True      0.05
16         17         71.70         novo       False      0.00
17         18         55.15   recorrente        True      0.05
18         19        263.81          vip       False      0.15
19         20        294.58   recorrente        True      0.10
20         21        261.21   recorrente        True      0.10
21         22        230.98         novo       False      0.10
22         23         36.71         novo        True      0.05
23         24         69.90          vip       False      0.15
24         25        279.92         novo       False      0.10
25         26        175.20         novo        True      0.10
26         27        125.27   recorrente        True      0.05
27         28        148.32          vip        True      0.15
28         29        204.16   recorrente       False      0.10
29         30        199.78   recorrente       False      0.10
30         31        199.37   recorrente       False      0.10
31         32        270.51         novo       False      0.10
32         33         30.65         novo       False      0.00
33         34        233.21   recorrente        True      0.10
34         35        287.99          vip       False      0.15
35         36        175.91          vip       False      0.15
36         37        232.31         novo       False      0.10
37         38         42.16         novo       False      0.00
38         39         48.17         novo        True      0.05
39         40        281.58         novo        True      0.10
40         41        213.82          vip        True      0.15
41         42        188.13          vip       False      0.15
42         43        198.03   recorrente       False      0.10
43         44        141.48          vip       False      0.15
44         45        245.03   recorrente        True      0.10

    valor_desconto  valor_final
0            25.37       228.34
1            17.29       155.66
2            20.74       186.66
3            18.20       103.11
4             0.00       113.62
5            19.90       179.05
6            23.43       132.76
7             0.00        94.26
8            24.60       221.39
9            42.37       240.07
10           19.80       112.20
11            3.29        62.46
12           38.51       218.23
13           20.76       117.66
14            0.00       118.46
15            6.54       124.24
16            0.00        71.70
17            2.76        52.39
18           39.57       224.24
19           29.46       265.12
20           26.12       235.09
21           23.10       207.88
22            1.84        34.87
23           10.49        59.41
24           27.99       251.93
25           17.52       157.68
26            6.26       119.01
27           22.25       126.07
28           20.42       183.74
29           19.98       179.80
30           19.94       179.43
31           27.05       243.46
32            0.00        30.65
33           23.32       209.89
34           43.20       244.79
35           26.39       149.52
36           23.23       209.08
37            0.00        42.16
38            2.41        45.76
39           28.16       253.42
40           32.07       181.75
41           28.22       159.91
42           19.80       178.23
43           21.22       120.26
44           24.50       220.53